import Head from 'next/head'
import { useSession, signOut, getSession } from 'next-auth/react'
import { NextPageContext } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { AiFillGithub } from 'react-icons/ai'
import { FaFacebook, FaLinkedin, FaYoutube } from 'react-icons/fa'
// eslint-disable-next-line import/no-unresolved
import SocialLink from '@/components/buttons/socialLink'
// eslint-disable-next-line import/no-unresolved
import ButtonWithAction from '@/components/buttons/buttonWithAction'

export default function Home() {
  const { data: session } = useSession()
  console.log('session in Home', session)
  const applicationInfos =
    'Application web permettant de se connecter avec les providers google, github, discord, ainsi que par email et mot de passe.'
  const SlackInfos =
    "Dans ce projet, j'ai utilisé React, Next.js, Typescript, NextAuth, MongoDB, Mongoose TailwindCSS et Bcrypt. "
  return (
    <div className="home bg-black min-h-screen text-white flex items-center justify-center">
      <Head>
        <title>Authentification avec next.js, nextauth et mongodb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" container mx-auto">
        <div className="border border-white relative flex flex-col w-full rounded-lg">
          <div className="flex flex-col justify-center items-center">
            <div className="w-full text-right">
              <div className="py-6 px-3">
                <Link
                  className="bg-blue-600 text-white hover:bg-blue-800 text-md uppercase font-bold px-8 py-2 rounded-md sm:mr-2 mb-1 ease-linear transition-all duration-150"
                  href="/lists"
                >
                  Mes litses
                </Link>
                <ButtonWithAction title="Se déconnecter" onClick={signOut} />
              </div>
            </div>
            <div className="w-full flex justify-center">
              <Image
                className="rounded-full h-48 w-48"
                src={session?.user?.image ?? '/auth/user.png'}
                width={192}
                height={192}
                alt={`photo de ${session?.user?.name}`}
              />
            </div>
            <div className="text-center mt-12">
              <h3 className="text-4xl font-semibold mb-2">
                {session?.user?.name}
              </h3>
              <div className="text-sm mb-2 font-bold">
                {session?.user?.email}
              </div>
              <div className="mb-2 mt-10">
                Vous êtes connecté avec &nbsp;
                <span className="capitalize bg-blue-400 text-white px-4 py-1 ml-2 font-bold italic text-lg rounded-md">
                  {session?.user?.provider}
                </span>
              </div>
            </div>
            <div className="mt-10 py-10 border-t text-center">
              <div className="flex flex-wrap justify-center">
                <div className="w-full px-4">
                  <p className="mb-4 text-sm">{applicationInfos}</p>
                  <p className="font-bold text-xs">{SlackInfos}</p>
                  <Link
                    rel="noopener noreferrer"
                    target="_blank"
                    className="mt-6 flex items-center justify-center"
                    href="https://github.com/Lugdu84/auth-next-mongodb"
                  >
                    Le code source du projet est disponible ici &nbsp;
                    <AiFillGithub size={24} />
                  </Link>
                  <div className="flex justify-center gap-4 mt-4 pt-6">
                    <SocialLink href="/" Icon={AiFillGithub} />
                    <SocialLink href="/" Icon={FaLinkedin} />
                    <SocialLink href="/" Icon={FaFacebook} />
                    <SocialLink href="/" Icon={FaYoutube} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)
  return {
    props: { session }, // will be passed to the page component as props
  }
}
