import Head from 'next/head'
import { useSession, signIn, signOut, getSession } from 'next-auth/react'
import { NextPageContext } from 'next'
import Image from 'next/image'

export default function Home() {
  const { data: session } = useSession()
  console.log('session', session)
  return (
    <div className="h-screen flex flex-col items-center justify-center space-y-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className=" text-red-400 text-4xl">
        Bonjour {session?.user?.name} !
      </h1>
      {session?.user?.image && (
        <Image
          className="rounded-full h-32 w-32"
          src={session?.user?.image as string}
          width={128}
          height={128}
          alt={`photo de profil de ${session?.user?.name}`}
          priority
        />
      )}
      <h4>{session?.user?.email}</h4>

      {session ? (
        <button
          type="button"
          className="bg-blue-400 text-white p-2 rounded-lg"
          onClick={() => signOut()}
        >
          Se déconnecter
        </button>
      ) : (
        <button
          className="bg-blue-400 text-white p-2 rounded-lg"
          type="button"
          onClick={() => signIn()}
        >
          Se connecter
        </button>
      )}
    </div>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)
  return {
    props: { session }, // will be passed to the page component as props
  }
}
